
svg:{R:|6 10*.:"\\c";n:10;.h.hta[`svg;`version`xmlns`viewBox!("1.2";"http://www.w3.org/2000/svg";" "/:$0 0,R)],(,/((.h.hta[`text;]'+$`x`y!+((-20 20+7*)'|:'p),p:(R%n)*/:0,/:n-!n),'$,/{x@(!y)*(#x)div y}[;n]'!:'b),\:"</text>"),(,/((-1_)'.h.hta[`polyline;]'+`fill`stroke`points!((#y)#,"none";y;" "/:'","/:''$+:'(20 0+)'R-/:x*\:R%b:{"j"$xexp[10;-_-:.q.xlog[10;max x]]}'*x)),\:"/>"),"</svg>"}
atob:{c:.q.mod[-#x;3];((-c)_.Q.b6[,/-4#',[0 0 0 0;]'64\:'256/:'"i"$0N 3#x,c#0]),c#"="};
plot:{t:svg[,x;"#",/:$(-1+#x)#`7fb148`58595b`6e75b5`f28030`22b6f0];-1"\033]1337;File=name=",atob["g.svg"],";size=",($#t),";width=100%;inline=1:",atob[t],"\007";}
