
svg:{R:|6 10*.:"\\c";n:10;.h.hta[`svg;`version`xmlns`viewBox!("1.2";"http://www.w3.org/2000/svg";" "/:$0 0,R)],(,/((.h.hta[`text;]'+$`x`y!+((0 20+6*)'|:'p),p:(R%n)*/:0,/:n-!n),'$,/{x@(!y)*(#x)div y}[;n]'!:'b),\:"</text>"),(,/((-1_)'.h.hta[`polyline;]'+`fill`stroke`points!((#y)#,"none";y;" "/:'","/:''$+:'(20 0+)'R-/:x*\:R%b:{"j"$xexp[10;-_-:.q.xlog[10;max x]]}'*x)),\:"/>"),"</svg>"}
plot:{(-.z.w)@(.z.slot;4h$svg[,x;"#",/:$(-1+#x)#`6E75B5`7FB148`F28030`22B6F0`58595B])}

